#include "ast.h"

DEFINE_ENUM_WITH_REPR(TypeKind, ENUMERATE_TYPES)

DEFINE_ENUM_WITH_REPR(UnopKind, ENUMERATE_UNOPS)

DEFINE_ENUM_WITH_REPR(BinopKind, ENUMERATE_BINOPS)

DEFINE_ENUM_WITH_REPR(ExprKind, ENUMERATE_EXPRS)

DEFINE_ENUM_WITH_REPR(StmtKind, ENUMERATE_STMTS)
